In [2]:
import numpy as np

np.__version__

'1.18.1'

In [3]:
import scipy

scipy.__version__

'1.4.1'

numpy - https://numpy.org/ written on C

scipy - https://www.scipy.org/ written on C, C++, and Fortran

# Python VS C/C++

In [4]:
a = list(range(1_000_000))

In [5]:
%%timeit
[e * e for e in a]

41.5 ms ± 177 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [6]:
a = np.arange(1_000_000)

In [7]:
%%timeit

a * a

554 µs ± 4.02 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


## loops, avoid loops, espessially nested loops

In [9]:
rows, cols = 1_000, 1_000

a = [list(range(i, i + cols)) for i in range(0, rows)]
b = [[0 for j in range(cols)] for i in range(rows)]

In [10]:
%%timeit

for i in range(rows):
    for j in range(cols):
        b[i][j] = 2 * a[i][j]

136 ms ± 67 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [11]:
a = np.asarray(a)

In [12]:
%%timeit

2 * a

777 µs ± 1.48 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


# Arrays in numpy

In [13]:
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [14]:
a = np.array([1,2,3,4,5], dtype=np.float64)
a

array([1., 2., 3., 4., 5.])

In [15]:
a = np.array([[1,2,3,4,5],
              [6,7,8,9,0]], dtype=float)
a

array([[1., 2., 3., 4., 5.],
       [6., 7., 8., 9., 0.]])

In [16]:
a.shape

(2, 5)

In [17]:
a.ndim

2

In [18]:
a.dtype

dtype('float64')

In [19]:
a.astype(int)

array([[1, 2, 3, 4, 5],
       [6, 7, 8, 9, 0]])

## Array dimension

In [20]:
a

array([[1., 2., 3., 4., 5.],
       [6., 7., 8., 9., 0.]])

In [21]:
a.dtype

dtype('float64')

In [22]:
a.dtype.itemsize # sizeof(float64)

8

In [28]:
## 8 bites

In [23]:
a.shape

(2, 5)

In [29]:
a.strides

(40, 8)

In [25]:
b = a.reshape(5, 2)
b

array([[1., 2.],
       [3., 4.],
       [5., 6.],
       [7., 8.],
       [9., 0.]])

In [26]:
b.shape

(5, 2)

In [27]:
b.strides

(16, 8)

In [32]:
a.reshape(-1,2)

array([[1., 2.],
       [3., 4.],
       [5., 6.],
       [7., 8.],
       [9., 0.]])

In [35]:
b = a.reshape(5, -1) # linked to the same data in memory, operation cost ~ 0
a[0, 1] = -10

b

array([[  1., -10.],
       [  3.,   4.],
       [  5.,   6.],
       [  7.,   8.],
       [  9.,   0.]])

In [36]:
b = a.flatten() # makes a copy and this copy will be one dimentional array
a[0, 1] = -20

b

array([  1., -10.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,   0.])

In [37]:
b = a.ravel() # linked to the same data in memory, presented as one dimentional array
a[0, 1] = -30

b

array([  1., -30.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,   0.])

In [38]:
c = a.T # same as a.transpose(), linked to the same data in memory
a[0, 1] = -40

c

array([[  1.,   6.],
       [-40.,   7.],
       [  3.,   8.],
       [  4.,   9.],
       [  5.,   0.]])

In [39]:
c.strides, a.strides

((8, 40), (40, 8))

In [40]:
b = np.arange(10)
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
b[np.newaxis, :] # same as b.reshape(1, *b.shape)

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [42]:
np.expand_dims(b, axis=0)

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [43]:
b[:, np.newaxis] # same as b.reshape(*b.shape, 1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [44]:
b[np.newaxis, :, np.newaxis].shape

(1, 10, 1)

## Create an Array with populated data

In [46]:
np.zeros(shape=(3, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [47]:
np.zeros_like(a)

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [48]:
np.ones(5) # same as np.ones(shape=(5,))

array([1., 1., 1., 1., 1.])

In [49]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [50]:
np.arange(1, 10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [51]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [52]:
np.arange(1,10,0.5)

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5, 7. ,
       7.5, 8. , 8.5, 9. , 9.5])

In [53]:
np.linspace(0, 1, 5, endpoint=True)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

## Array copy

In [55]:
a = np.array([1,2,3,4,5], dtype=np.float32)
b = np.asarray(a)
c = np.array(a)

b, c

(array([1., 2., 3., 4., 5.], dtype=float32),
 array([1., 2., 3., 4., 5.], dtype=float32))

In [56]:
a[0] = 0

b, c

(array([0., 2., 3., 4., 5.], dtype=float32),
 array([1., 2., 3., 4., 5.], dtype=float32))

In [57]:
a = np.array([1,2,3,4,5], dtype=np.float32)
b = np.asarray(a, dtype=np.int32)
c = np.array(a)

a, b, c

(array([1., 2., 3., 4., 5.], dtype=float32),
 array([1, 2, 3, 4, 5], dtype=int32),
 array([1., 2., 3., 4., 5.], dtype=float32))

In [58]:
a[0] = 0

a, b, c

(array([0., 2., 3., 4., 5.], dtype=float32),
 array([1, 2, 3, 4, 5], dtype=int32),
 array([1., 2., 3., 4., 5.], dtype=float32))

In [59]:
d = [1,2,3,4,5]
a = np.asarray(d)

d[0] = 0
a

array([1, 2, 3, 4, 5])

In [60]:
np.copy(a)

array([1, 2, 3, 4, 5])

# Array operations

## Scalar and unary operations

In [61]:
a = np.arange(10).reshape(2, -1)

a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [62]:
a ** 3 # same as np.power(a, 3)

array([[  0,   1,   8,  27,  64],
       [125, 216, 343, 512, 729]])

In [63]:
a + 2 # same as np.add(a, 2)

array([[ 2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11]])

In [64]:
2 * a # same as np.multyply(2, a)

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18]])

In [65]:
np.sqrt(a)

array([[0.        , 1.        , 1.41421356, 1.73205081, 2.        ],
       [2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ]])

In [66]:
np.exp(a)

array([[1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
        5.45981500e+01],
       [1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
        8.10308393e+03]])

In [67]:
np.log(1 + a)

array([[0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791],
       [1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509]])

In [68]:
np.log2(1 + a)

array([[0.        , 1.        , 1.5849625 , 2.        , 2.32192809],
       [2.5849625 , 2.80735492, 3.        , 3.169925  , 3.32192809]])

In [69]:
np.sin(a)

array([[ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ],
       [-0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849]])

In [70]:
a  > 0 # same as np.greater(a, 0)

array([[False,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

## Aggregate operations

In [75]:
np.random.seed(5656)
a = np.random.randint(0, 10, size=(7,))
a[3] = 10

a

array([ 4,  6,  7, 10,  0,  3,  5])

In [76]:
a.min(), a.max(), a.argmax(), a.sum(), a.prod(), a.mean()

(0, 10, 3, 35, 0, 5.0)

In [77]:
np.min(a), np.max(a), np.argmax(a), np.sum(a), np.prod(a), np.mean(a)

(0, 10, 3, 35, 0, 5.0)

In [83]:
np.random.seed(5555)
a = np.random.randint(0, 10, size=(3, 7))
a[1, 3] = 15

a

array([[ 2,  3,  0,  5,  2,  0,  3],
       [ 8,  8,  0, 15,  1,  5,  3],
       [ 0,  1,  6,  2,  1,  4,  5]])

In [84]:
a.max()

15

In [80]:
a.max(axis=0)

array([ 8,  8,  6, 15,  2,  5,  5])

In [81]:
a.sum(axis=1)

array([15, 40, 19])

In [82]:
a

array([[ 2,  3,  0,  5,  2,  0,  3],
       [ 8,  8,  0, 15,  1,  5,  3],
       [ 0,  1,  6,  2,  1,  4,  5]])

In [85]:
a.argmax()

10

In [86]:
a.ravel()[a.argmax()]

15

In [87]:
i = np.argmax(a)
i ,j = i // a.shape[1], i % a.shape[1]

print("value =", a[i, j])
print("index =", (i, j))

value = 15
index = (1, 3)


In [88]:
np.unravel_index(np.argmax(a), a.shape)

(1, 3)

## Who is faster?

In [89]:
b = np.random.randint(0, 10, size=(1_000, 1_000))
b[36, 42] = 20
b = b.ravel()

In [90]:
%%timeit

b.max()

897 µs ± 2.49 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [92]:
%%timeit

max(b)

105 ms ± 88.6 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


## Unary operations in boolean arrays

In [94]:
a = np.asarray([True, True, False, False, True])

a

array([ True,  True, False, False,  True])

In [95]:
a.any(), np.any(a)

(True, True)

In [96]:
a.all(), np.all(a)

(False, False)

In [98]:
a = np.asarray([[True, True, False, False, True],
               [True, False, False, True, False]])

a

array([[ True,  True, False, False,  True],
       [ True, False, False,  True, False]])

In [99]:
a.any(axis=0)

array([ True,  True, False,  True,  True])

In [100]:
a.all(axis=1)

array([False, False])

In [101]:
np.logical_not(a)

array([[False, False,  True,  True, False],
       [False,  True,  True, False,  True]])

In [102]:
~a # bitwise; same as np.bitwise_not(a)

array([[False, False,  True,  True, False],
       [False,  True,  True, False,  True]])

## Binary operations

In [103]:
a = a.astype(int)

a

array([[1, 1, 0, 0, 1],
       [1, 0, 0, 1, 0]])

In [104]:
np.random.seed(4986)
b = np.random.randint(0, 10, size=a.shape)

b

array([[5, 5, 3, 2, 2],
       [3, 2, 5, 6, 3]])

In [105]:
a * b # same as np.multiply(a, b)

array([[5, 5, 0, 0, 2],
       [3, 0, 0, 6, 0]])

In [106]:
a + b # same as np.add(a, b)

array([[6, 6, 3, 2, 3],
       [4, 2, 5, 7, 3]])

In [107]:
a

array([[1, 1, 0, 0, 1],
       [1, 0, 0, 1, 0]])

In [108]:
b

array([[5, 5, 3, 2, 2],
       [3, 2, 5, 6, 3]])

In [109]:
np.fmax(a, b) # element-wise maximum

array([[5, 5, 3, 2, 2],
       [3, 2, 5, 6, 3]])

In [110]:
a > b # same as np.greater(a, b)

array([[False, False, False, False, False],
       [False, False, False, False, False]])

In [112]:
np.random.seed(4689)
a = np.random.random(size=(2, 5))
b = a + np.random.random(size=(2, 5)) * 1e-5

In [113]:
a

array([[0.8184218 , 0.17598382, 0.02284224, 0.19893591, 0.89972128],
       [0.97083721, 0.1866481 , 0.94422355, 0.24332621, 0.73618167]])

In [114]:
b

array([[0.81842551, 0.17598394, 0.02284872, 0.19894088, 0.89972311],
       [0.97084591, 0.18665273, 0.94422544, 0.24333618, 0.73618996]])

In [115]:
np.isclose(a, b)

array([[ True,  True, False, False,  True],
       [ True, False,  True, False, False]])

In [116]:
np.allclose(a, b) # same as np.isclose(a, b).all()

False

In [117]:
np.isclose(a, b).any()

True

In [118]:
np.random.seed(4783)
a = (np.random.random(size=(5,)) - 0.5) * 1e-7
np.isclose(a, 0, atol=1e-6)

array([ True,  True,  True,  True,  True])